// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetworkPacket.proto

package com.gora.server.model.network.protobuf;

public final class NetworkPacketProtoBuf {
  private NetworkPacketProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.NetworkPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>required bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>required fixed32 type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required fixed32 type = 2;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>required fixed32 dataSize = 3;</code>
     * @return Whether the dataSize field is set.
     */
    boolean hasDataSize();
    /**
     * <code>required fixed32 dataSize = 3;</code>
     * @return The dataSize.
     */
    int getDataSize();

    /**
     * <code>required string channelId = 4;</code>
     * @return Whether the channelId field is set.
     */
    boolean hasChannelId();
    /**
     * <code>required string channelId = 4;</code>
     * @return The channelId.
     */
    java.lang.String getChannelId();
    /**
     * <code>required string channelId = 4;</code>
     * @return The bytes for channelId.
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>required string identify = 5;</code>
     * @return Whether the identify field is set.
     */
    boolean hasIdentify();
    /**
     * <code>required string identify = 5;</code>
     * @return The identify.
     */
    java.lang.String getIdentify();
    /**
     * <code>required string identify = 5;</code>
     * @return The bytes for identify.
     */
    com.google.protobuf.ByteString
        getIdentifyBytes();

    /**
     * <code>required fixed32 totalSize = 6;</code>
     * @return Whether the totalSize field is set.
     */
    boolean hasTotalSize();
    /**
     * <code>required fixed32 totalSize = 6;</code>
     * @return The totalSize.
     */
    int getTotalSize();

    /**
     * <code>required fixed32 sequence = 7;</code>
     * @return Whether the sequence field is set.
     */
    boolean hasSequence();
    /**
     * <code>required fixed32 sequence = 7;</code>
     * @return The sequence.
     */
    int getSequence();
  }
  /**
   * Protobuf type {@code protobuf.NetworkPacket}
   */
  public static final class NetworkPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.NetworkPacket)
      NetworkPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkPacket.newBuilder() to construct.
    private NetworkPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkPacket() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      channelId_ = "";
      identify_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.class, com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes data = 1;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>required fixed32 type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required fixed32 type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int dataSize_ = 0;
    /**
     * <code>required fixed32 dataSize = 3;</code>
     * @return Whether the dataSize field is set.
     */
    @java.lang.Override
    public boolean hasDataSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required fixed32 dataSize = 3;</code>
     * @return The dataSize.
     */
    @java.lang.Override
    public int getDataSize() {
      return dataSize_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object channelId_ = "";
    /**
     * <code>required string channelId = 4;</code>
     * @return Whether the channelId field is set.
     */
    @java.lang.Override
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string channelId = 4;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelId = 4;</code>
     * @return The bytes for channelId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTIFY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object identify_ = "";
    /**
     * <code>required string identify = 5;</code>
     * @return Whether the identify field is set.
     */
    @java.lang.Override
    public boolean hasIdentify() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string identify = 5;</code>
     * @return The identify.
     */
    @java.lang.Override
    public java.lang.String getIdentify() {
      java.lang.Object ref = identify_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identify_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string identify = 5;</code>
     * @return The bytes for identify.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentifyBytes() {
      java.lang.Object ref = identify_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identify_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALSIZE_FIELD_NUMBER = 6;
    private int totalSize_ = 0;
    /**
     * <code>required fixed32 totalSize = 6;</code>
     * @return Whether the totalSize field is set.
     */
    @java.lang.Override
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required fixed32 totalSize = 6;</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public int getTotalSize() {
      return totalSize_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 7;
    private int sequence_ = 0;
    /**
     * <code>required fixed32 sequence = 7;</code>
     * @return Whether the sequence field is set.
     */
    @java.lang.Override
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required fixed32 sequence = 7;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdentify()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFixed32(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFixed32(3, dataSize_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, channelId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, identify_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFixed32(6, totalSize_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeFixed32(7, sequence_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, dataSize_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, channelId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, identify_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, totalSize_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(7, sequence_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket)) {
        return super.equals(obj);
      }
      com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket other = (com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket) obj;

      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasDataSize() != other.hasDataSize()) return false;
      if (hasDataSize()) {
        if (getDataSize()
            != other.getDataSize()) return false;
      }
      if (hasChannelId() != other.hasChannelId()) return false;
      if (hasChannelId()) {
        if (!getChannelId()
            .equals(other.getChannelId())) return false;
      }
      if (hasIdentify() != other.hasIdentify()) return false;
      if (hasIdentify()) {
        if (!getIdentify()
            .equals(other.getIdentify())) return false;
      }
      if (hasTotalSize() != other.hasTotalSize()) return false;
      if (hasTotalSize()) {
        if (getTotalSize()
            != other.getTotalSize()) return false;
      }
      if (hasSequence() != other.hasSequence()) return false;
      if (hasSequence()) {
        if (getSequence()
            != other.getSequence()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasDataSize()) {
        hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
        hash = (53 * hash) + getDataSize();
      }
      if (hasChannelId()) {
        hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
        hash = (53 * hash) + getChannelId().hashCode();
      }
      if (hasIdentify()) {
        hash = (37 * hash) + IDENTIFY_FIELD_NUMBER;
        hash = (53 * hash) + getIdentify().hashCode();
      }
      if (hasTotalSize()) {
        hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getTotalSize();
      }
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + getSequence();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.NetworkPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.NetworkPacket)
        com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.class, com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.Builder.class);
      }

      // Construct using com.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        type_ = 0;
        dataSize_ = 0;
        channelId_ = "";
        identify_ = "";
        totalSize_ = 0;
        sequence_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
      }

      @java.lang.Override
      public com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket getDefaultInstanceForType() {
        return com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.getDefaultInstance();
      }

      @java.lang.Override
      public com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket build() {
        com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket buildPartial() {
        com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket result = new com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dataSize_ = dataSize_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.channelId_ = channelId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.identify_ = identify_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.totalSize_ = totalSize_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sequence_ = sequence_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket) {
          return mergeFrom((com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket other) {
        if (other == com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDataSize()) {
          setDataSize(other.getDataSize());
        }
        if (other.hasChannelId()) {
          channelId_ = other.channelId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasIdentify()) {
          identify_ = other.identify_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasData()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasDataSize()) {
          return false;
        }
        if (!hasChannelId()) {
          return false;
        }
        if (!hasIdentify()) {
          return false;
        }
        if (!hasTotalSize()) {
          return false;
        }
        if (!hasSequence()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                type_ = input.readFixed32();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                dataSize_ = input.readFixed32();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 34: {
                channelId_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                identify_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 53: {
                totalSize_ = input.readFixed32();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 61: {
                sequence_ = input.readFixed32();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 1;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required fixed32 type = 2;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required fixed32 type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>required fixed32 type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private int dataSize_ ;
      /**
       * <code>required fixed32 dataSize = 3;</code>
       * @return Whether the dataSize field is set.
       */
      @java.lang.Override
      public boolean hasDataSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required fixed32 dataSize = 3;</code>
       * @return The dataSize.
       */
      @java.lang.Override
      public int getDataSize() {
        return dataSize_;
      }
      /**
       * <code>required fixed32 dataSize = 3;</code>
       * @param value The dataSize to set.
       * @return This builder for chaining.
       */
      public Builder setDataSize(int value) {

        dataSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 dataSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataSize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>required string channelId = 4;</code>
       * @return Whether the channelId field is set.
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string channelId = 4;</code>
       * @return The channelId.
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string channelId = 4;</code>
       * @return The bytes for channelId.
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelId = 4;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        channelId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        channelId_ = getDefaultInstance().getChannelId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string channelId = 4;</code>
       * @param value The bytes for channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        channelId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object identify_ = "";
      /**
       * <code>required string identify = 5;</code>
       * @return Whether the identify field is set.
       */
      public boolean hasIdentify() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string identify = 5;</code>
       * @return The identify.
       */
      public java.lang.String getIdentify() {
        java.lang.Object ref = identify_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            identify_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string identify = 5;</code>
       * @return The bytes for identify.
       */
      public com.google.protobuf.ByteString
          getIdentifyBytes() {
        java.lang.Object ref = identify_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identify_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string identify = 5;</code>
       * @param value The identify to set.
       * @return This builder for chaining.
       */
      public Builder setIdentify(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        identify_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required string identify = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentify() {
        identify_ = getDefaultInstance().getIdentify();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>required string identify = 5;</code>
       * @param value The bytes for identify to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        identify_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int totalSize_ ;
      /**
       * <code>required fixed32 totalSize = 6;</code>
       * @return Whether the totalSize field is set.
       */
      @java.lang.Override
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required fixed32 totalSize = 6;</code>
       * @return The totalSize.
       */
      @java.lang.Override
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>required fixed32 totalSize = 6;</code>
       * @param value The totalSize to set.
       * @return This builder for chaining.
       */
      public Builder setTotalSize(int value) {

        totalSize_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 totalSize = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        totalSize_ = 0;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <code>required fixed32 sequence = 7;</code>
       * @return Whether the sequence field is set.
       */
      @java.lang.Override
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required fixed32 sequence = 7;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>required fixed32 sequence = 7;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 sequence = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sequence_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.NetworkPacket)
    }

    // @@protoc_insertion_point(class_scope:protobuf.NetworkPacket)
    private static final com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket();
    }

    public static com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetworkPacket>
        PARSER = new com.google.protobuf.AbstractParser<NetworkPacket>() {
      @java.lang.Override
      public NetworkPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetworkPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gora.server.model.network.protobuf.NetworkPacketProtoBuf.NetworkPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_NetworkPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_NetworkPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023NetworkPacket.proto\022\010protobuf\"\207\001\n\rNetw" +
      "orkPacket\022\014\n\004data\030\001 \002(\014\022\014\n\004type\030\002 \002(\007\022\020\n" +
      "\010dataSize\030\003 \002(\007\022\021\n\tchannelId\030\004 \002(\t\022\020\n\010id" +
      "entify\030\005 \002(\t\022\021\n\ttotalSize\030\006 \002(\007\022\020\n\010seque" +
      "nce\030\007 \002(\007B6\n\035com.gora.server.model.netwo" +
      "rkB\025NetworkPacketProtoBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_NetworkPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_NetworkPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_NetworkPacket_descriptor,
        new java.lang.String[] { "Data", "Type", "DataSize", "ChannelId", "Identify", "TotalSize", "Sequence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
