app:
  udp_server_port: 11111
  udp_client_port: 11112
  tcp_server_port: 11200
  max_client: 1
  secret-key: ${JWT_SECRET_KEY}
  tcp_accept_thread_count: ${TCP_ACCEPT_THREAD_COUNT}
  tcp_event_thread_count: ${TCP_EVENT_THREAD_COUNT}
  udp_accept_event_thread_count: ${UDP_ACCEPT_EVENT_THREAD_COUNT}
  clientDataBufferExpireTime: ${CLIENT_DATA_BUFFER_EXPIRE_TIME}
  clientDataBufferCleanDelay: ${CLIENT_DATA_BUFFER_CLEAN_DELAY}


# spy db log
decorator:
  datasource:
    p6spy:
      enable-logging: true
        
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect