app:
  udp_server_port: ${UDP_SERVER_PORT:11111}
  udp_client_port: ${UDP_CLIENT_PORT:11112}
  tcp_server_port: ${TCP_SERVER_PORT:11200}
  max_client: 1
  secret-key: ${JWT_SECRET_KEY}

# spy db log
decorator:
  datasource:
    p6spy:
      enable-logging: true
        
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect