// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eServiceRouteType.proto

// Protobuf Java Version: 3.25.0-rc2
package org.gora.server.model.network;

public final class eServiceRouteTypeProtoBuf {
  private eServiceRouteTypeProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protobuf.eServiceRouteType}
   */
  public enum eServiceRouteType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>player_coordinate = 1;</code>
     */
    player_coordinate(1),
    /**
     * <code>health_check = 2;</code>
     */
    health_check(2),
    ;

    /**
     * <code>player_coordinate = 1;</code>
     */
    public static final int player_coordinate_VALUE = 1;
    /**
     * <code>health_check = 2;</code>
     */
    public static final int health_check_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static eServiceRouteType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static eServiceRouteType forNumber(int value) {
      switch (value) {
        case 1: return player_coordinate;
        case 2: return health_check;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<eServiceRouteType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        eServiceRouteType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<eServiceRouteType>() {
            public eServiceRouteType findValueByNumber(int number) {
              return eServiceRouteType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.gora.server.model.network.eServiceRouteTypeProtoBuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final eServiceRouteType[] VALUES = values();

    public static eServiceRouteType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private eServiceRouteType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.eServiceRouteType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027eServiceRouteType.proto\022\010protobuf*<\n\021e" +
      "ServiceRouteType\022\025\n\021player_coordinate\020\001\022" +
      "\020\n\014health_check\020\002B:\n\035org.gora.server.mod" +
      "el.networkB\031eServiceRouteTypeProtoBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
