// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetworkPacket.proto

package org.gora.server.model.network;

public final class NetworkPacketProtoBuf {
  private NetworkPacketProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.NetworkPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>required .protobuf.eServiceRouteType type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .protobuf.eServiceRouteType type = 2;</code>
     * @return The type.
     */
    org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType getType();

    /**
     * <code>required int32 totalSize = 3;</code>
     * @return Whether the totalSize field is set.
     */
    boolean hasTotalSize();
    /**
     * <code>required int32 totalSize = 3;</code>
     * @return The totalSize.
     */
    int getTotalSize();
  }
  /**
   * Protobuf type {@code protobuf.NetworkPacket}
   */
  public static final class NetworkPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.NetworkPacket)
      NetworkPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkPacket.newBuilder() to construct.
    private NetworkPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkPacket() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkPacket();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gora.server.model.network.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gora.server.model.network.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.class, org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 1;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 1;
    /**
     * <code>required .protobuf.eServiceRouteType type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .protobuf.eServiceRouteType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType getType() {
      org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType result = org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType.forNumber(type_);
      return result == null ? org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType.player_coordinate : result;
    }

    public static final int TOTALSIZE_FIELD_NUMBER = 3;
    private int totalSize_ = 0;
    /**
     * <code>required int32 totalSize = 3;</code>
     * @return Whether the totalSize field is set.
     */
    @java.lang.Override
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 totalSize = 3;</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public int getTotalSize() {
      return totalSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, totalSize_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket)) {
        return super.equals(obj);
      }
      org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket other = (org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket) obj;

      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasTotalSize() != other.hasTotalSize()) return false;
      if (hasTotalSize()) {
        if (getTotalSize()
            != other.getTotalSize()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasTotalSize()) {
        hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getTotalSize();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.NetworkPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.NetworkPacket)
        org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gora.server.model.network.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gora.server.model.network.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.class, org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.Builder.class);
      }

      // Construct using org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        type_ = 1;
        totalSize_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gora.server.model.network.NetworkPacketProtoBuf.internal_static_protobuf_NetworkPacket_descriptor;
      }

      @java.lang.Override
      public org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket getDefaultInstanceForType() {
        return org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.getDefaultInstance();
      }

      @java.lang.Override
      public org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket build() {
        org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket buildPartial() {
        org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket result = new org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalSize_ = totalSize_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket) {
          return mergeFrom((org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket other) {
        if (other == org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasTotalSize()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                int tmpRaw = input.readEnum();
                org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType tmpValue =
                    org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  type_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 24: {
                totalSize_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 1;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .protobuf.eServiceRouteType type = 2;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .protobuf.eServiceRouteType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType getType() {
        org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType result = org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType.forNumber(type_);
        return result == null ? org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType.player_coordinate : result;
      }
      /**
       * <code>required .protobuf.eServiceRouteType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.gora.server.model.network.eServiceRouteTypeProtoBuf.eServiceRouteType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.eServiceRouteType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
        onChanged();
        return this;
      }

      private int totalSize_ ;
      /**
       * <code>required int32 totalSize = 3;</code>
       * @return Whether the totalSize field is set.
       */
      @java.lang.Override
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 totalSize = 3;</code>
       * @return The totalSize.
       */
      @java.lang.Override
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>required int32 totalSize = 3;</code>
       * @param value The totalSize to set.
       * @return This builder for chaining.
       */
      public Builder setTotalSize(int value) {

        totalSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 totalSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.NetworkPacket)
    }

    // @@protoc_insertion_point(class_scope:protobuf.NetworkPacket)
    private static final org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket();
    }

    public static org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetworkPacket>
        PARSER = new com.google.protobuf.AbstractParser<NetworkPacket>() {
      @java.lang.Override
      public NetworkPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetworkPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gora.server.model.network.NetworkPacketProtoBuf.NetworkPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_NetworkPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_NetworkPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023NetworkPacket.proto\022\010protobuf\032\027eServic" +
      "eRouteType.proto\"[\n\rNetworkPacket\022\014\n\004dat" +
      "a\030\001 \001(\014\022)\n\004type\030\002 \002(\0162\033.protobuf.eServic" +
      "eRouteType\022\021\n\ttotalSize\030\003 \002(\005B6\n\035org.gor" +
      "a.server.model.networkB\025NetworkPacketPro" +
      "toBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.gora.server.model.network.eServiceRouteTypeProtoBuf.getDescriptor(),
        });
    internal_static_protobuf_NetworkPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_NetworkPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_NetworkPacket_descriptor,
        new java.lang.String[] { "Data", "Type", "TotalSize", });
    org.gora.server.model.network.eServiceRouteTypeProtoBuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
